### ISSUE TITLE
source organization

### ISSUE THREAD

**Issue by relascope** [ivareske/QtInternetRadio#1]
as you kind of depend on presets.xml it would be fine for developers if it is included in repository. 

adding to your .pro file
CONFIG += debug_and_release

lets you debug from QtCreator.

**Comment by ivareske** [comment]
Hi, I did not included it on purpose, as this is a file that comes with another radio program.... It comes with screamer radio:
http://www.screamer-radio.com/
I was worried I might violate some copyright laws or something if I included it.
Just install screamer radio and you can find it in the installation folder. 
One can still choose between release and debug mode in Qt creator without specifying any debug or release flags to CONFIG. Qt creator manages this depending on if the release or debug tab is chosen in the Qt creator GUI.
By the way, this is just a hobby project I made one weekend, it is not tested thoroughly at all...
Best regards, Ivar
